[project]
name = "auto-healer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Anya", email = "anya.shah21@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "opentelemetry-api>=1.39.1",
    "opentelemetry-exporter-otlp-proto-http>=1.39.1",
    "opentelemetry-sdk>=1.39.1",
]

[project.scripts]
auto-healer = "auto_healer:main"

[build-system]
requires = ["uv_build>=0.10.8,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
